name: Feature pull-request

on:
  pull_request:
    branches-ignore:
      - main
      - master

jobs:
  feature-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: prepare variables
        run: |
          PULL_ID=$(echo $GITHUB_REF | awk '{split($0,a,"/"); print a[3]}')
          echo "PULL_ID=$PULL_ID" >> $GITHUB_ENV
      - name: notify on webhook
        run: |
          DATA="{
            \"embeds\": [
              {
                \"title\": \"Feature merge\",
                \"description\": \"\\\"$GITHUB_ACTOR\\\" möchte den Feature-Branch \\\"$GITHUB_HEAD_REF\\\" in Version \\\"$GITHUB_BASE_REF\\\" mergen\",
                \"color\": 4934655,
                \"author\": {
                  \"name\": \"Github-Status\",
                  \"url\": \"https://github.com/Akkjon/GummiBot\",
                  \"icon_url\": \"https://cdn.afterdawn.fi/v3/news/original/github-logo.png\"
                }
              }, {
                   \"title\":\"Anschauen\",
                   \"url\":\"https://github.com/Akkjon/GummiBot/pull/${{ env.PULL_ID }}\",
                \"color\": 4934655
              }
            ]
          }"
          curl -X POST -d "$DATA" -H "Content-Type: application/json" https://discord.com/api/webhooks/${{ secrets.DISCORD_SERVER }}/${{ secrets.DISCORD_WEBHOOK_GITHUB }}
