# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    #- name: pwd
    #  run: pwd
    - name: Build with Maven
      #run: mvn -B package --file Discord-Bot-MusicbotRemoveMessage/pom.xml
      run: mvn -B package
      
    - uses: actions/upload-artifact@v2
      with:
        name: bot
        path: /home/runner/work/GummiBot/GummiBot/target/GummiBot-**-jar-with-dependencies.jar # or path/to/artifact
