# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Pipeline

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'None'  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Replace token
      env:
        TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: sed -i "s/\[token\]/$TOKEN/" src/de/akkjon/pr/mbrm/Main.java
    - name: Build with Maven
      run: mvn -B package
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: bot
        path: /home/runner/work/GummiBot/GummiBot/target/GummiBot-**-jar-with-dependencies.jar # or path/to/artifact
